In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

In [4]:
type(x)

numpy.ndarray

In [5]:
x.ndim

1

In [6]:
x=np.array([(1,2,3),(4,5,6)])

In [7]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
x.ndim

2

In [9]:
x.shape

(2, 3)

In [10]:
x.size

6

In [11]:
x.itemsize

4

In [12]:
x.size*x.itemsize

24

In [13]:
x.dtype

dtype('int32')

In [17]:
import sys

l1=list(range(1,1001))
a1=np.arange(1,1001, dtype='int32')

print("LIST SIZE:",sys.getsizeof(5)*len(l1))
print("ARRAY SIZE:",a1.size*a1.itemsize)


LIST SIZE: 28000
ARRAY SIZE: 4000


In [19]:
import time

SIZE=100000

l1=range(SIZE)
l2=range(SIZE)

a1=np.arange(SIZE)
a2=np.arange(SIZE)

start=time.time()
[x+y  for x,y in zip(l1,l2)]
end=time.time()
print("LIST TOOK: ",(end-start)*1000)

start=time.time()
result=a1+a2
end=time.time()
print("ARRAY TOOK: ",(end-start)*1000)



LIST TOOK:  9.924888610839844
ARRAY TOOK:  1.0118484497070312


In [23]:
a=np.array([(1,2,3,4),(5,6,7,8),(9,10,11,12)])

In [24]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
a[1,1]

6

In [27]:
a[2,2]

11

In [30]:
a[1:,1]

array([ 6, 10])

In [31]:
a[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [32]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
a.min()

1

In [35]:
a.max()

12

In [36]:
a.sum()

78

In [37]:
a.sum(axis=1)

array([10, 26, 42])

In [38]:
a.sum(axis=0)

array([15, 18, 21, 24])

In [40]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [41]:
np.std(a)

3.452052529534663

In [42]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292]])

In [43]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003],
       [-0.91113026, -0.83907153,  0.0044257 ,  0.84385396]])

In [44]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [45]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [46]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [47]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [49]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [50]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [51]:
x=np.array([(1,2,3,4),(5,6,7,8)])

In [52]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [53]:
x.shape

(2, 4)

In [54]:
x.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [55]:
a=np.array([(1,2,3,4),(5,6,7,8)])
b=np.array([(1,2,3,4),(5,6,7,8)])

In [56]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [58]:
a+b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [59]:
a-b

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [60]:
a.shape

(2, 4)

In [61]:
b.shape

(2, 4)

In [62]:
np.dot(a,b)

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [63]:
x=np.array([(1,2,3),(4,5,6),(7,8,9)])
y=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [66]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
x.shape

(3, 3)

In [65]:
y.shape

(3, 3)

In [68]:
np.dot(x,y)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])